from.decision_record import DecisionRecord

class BloomGenerator:
    def generate_model(self, prompt: str, record: DecisionRecord) -> dict:
        model_sql = f"-- Generated by Bloom\n-- Prompt: {prompt}\n-- Decision: {record.id}\n\nSELECT * FROM {{{{ ref('stg_users') }}}}"
        schema_yml = f"""version: 2
models:
    - name: {record.related_model}
    description: "{record.title}"
    columns:
            - name: user_id
        description: "Primary key"
        tests:
                    - unique
                    - not_null
"""
        return {
            "model.sql": model_sql,
            "schema.yml": schema_yml,
            "decision_record.md": record.to_markdown()
        }
